### ISSUE TITLE
GNOME install error on ubuntu

### ISSUE THREAD

**Issue by hnczhjh** [Websoft9/linuxscript#14]
### Bug Screenshot

![image](https://user-images.githubusercontent.com/86603933/128112847-69b1af94-aa7e-49e3-aa35-ad194d4ce49e.png)

![image](https://user-images.githubusercontent.com/86603933/128112952-bd5a07cb-0137-48bd-8612-6fda1641605f.png)

![image](https://user-images.githubusercontent.com/86603933/128113115-b41e3851-58c2-4062-963f-887a1057d84c.png)

**Comment by qiaofeng1227** [comment]
https://linuxconfig.org/how-to-install-gnome-on-ubuntu-20-04-lts-focal-fossa/

**Comment by chendelin1982** [comment]
Final solution: only need to run command `apt install gnome` which is a Ubuntu [official package](https://packages.ubuntu.com/focal/gnome)

**Comment by geraintlyu** [comment]
GNOME install error on ubuntu
1. use vnc to connect to the server, an error will be reported
![ubuntu-vnc](https://user-images.githubusercontent.com/53968450/128955704-4abbd6da-a97a-4390-b2d1-9319cef71249.png)

2. Use the remote software that comes with Windows to connect, only the root user can be used
![ubuntu-GNOME](https://user-images.githubusercontent.com/53968450/128955718-71bb3852-8de4-4b42-93b6-a002034dce43.png)

3. Use the remote software that comes with Windows to connect, can't user commen user
![fy-ubuntu](https://user-images.githubusercontent.com/53968450/128959073-7ecf076b-07f7-4a9b-89f7-779f59c4aabe.png)

**Comment by geraintlyu** [comment]
when test in AWS Ubuntu will get the same result.
1. user vnc to connect
![aws-vnc](https://user-images.githubusercontent.com/53968450/128960801-7a1d2975-07d1-457e-80f1-b13adb9f7ce8.png)
2. user the remote software that comes with Windows to connect
![aws-ubuntu](https://user-images.githubusercontent.com/53968450/128960863-49bc1519-a87e-4dd1-8ae9-25164d44021b.png)
