### ISSUE TITLE
Supplement to EN version

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/linuxscript#16]
## Language

- [ ] Chinese
- [x] English

## New content

The Documentation of Linux GUI Desktop Environment: **GNOME**, **KDE Plasma**, **MATE** and **Xfce** 

* URL: support.websoft9.com/docs/linux

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by chendelin1982** [comment]
Done, refer to: https://support.websoft9.com/docs/linux/admin-desktop.html
